# Site
repository: zmt28/zmt28.github.io
favicon: images/favicon.ico

# Personal info
name: Zion Taber
title: Business Analytics & Management Information Systems Major
email: ziontaber@gmail.com
website: https://zmt28.github.io

# Social links
# twitter_username: jekyll
github_username:  zmt28
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: zion-taber
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: Images/IMG_3764.png
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Zion Taber and I am a Junior at Drexel University studying business analytics and management information systems. I am interested in in big data, cloud computing, and consulting.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Hiking
   - Hackathons


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
