# Site
repository: zmt28/zmt28.github.io
favicon: images/favicon.ico

# Personal info
name: Zion Taber
title: Business Analytics & Management Information Systems Major
email: ziontaber@gmail.com
website: https://zmt28.github.io

# Social links
# twitter_username: jekyll
github_username:  zmt28
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: zion-taber
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: IMG_3764.jpeg
about_content: |
  Hello! My name is Zion Taber and I am a Junior at Drexel University studying business analytics and management information systems. 
  I am passionate about using big data and cloud computing to create business value. I'm active on campus as the president of the Drexel 
  Consulting Group and as a coordinator for Dragonhacks, Drexel's student run hackathon.
  
  I have worked with a range of different frameworks and technologies and I am always looking for opportunities to learn
  with something new. The things that I currently have the most experience working with are:
  <mark>R</mark>,
  <mark>Python</mark>,
  <mark>SQL</mark>,
  <mark>Bash</mark>,
  <mark>PowerBI</mark>,
  <mark>Excel</mark>,
  <mark>Docker</mark>,
  <mark>Git</mark>,
  <mark>Azure</mark> and
  <mark>AWS</mark> services.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
educaton_title: Education & Certificates

# More Section
more_title: Outside of Work
more_content: | # this will include new lines to allow paragraphs
  - Outside of work and school I enjoy rock climbing, backpacking, traveling to new places, and trying new types of cuisine!

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
